spring:
  application:
    name: Technical challenge API
  data:
    rest:
      basePath: /api
      detection-strategy: annotated
  datasource:
    url: jdbc:h2:mem:appDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    database: h2
