spring:
  application:
    name: Technical challenge API
  data:
    rest:
      basePath: /api
      detection-strategy: annotated
  datasource:
    url: jdbc:h2:mem:appDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    database: h2
  security:    jwt:
      header: Authorization
      secret: SecretKey
      expiration: 864_000_00 # 1 day in milliseconds
      prefix: Bearer
logging:
  file: ./logs/server.log
  group:
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
  level:
    root: WARN
    com.applaudostudios: TRACE
    org.hibernate: ERROR
    org.hibernate.SQL: INFO
    org.springframework.web: DEBUG
