CREATE ROLE challenge WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'admin$1';

CREATE DATABASE "appDB"
    WITH 
    OWNER = challenge
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;
